export const DECODE_BYTECODE = "DECODE_BYTECODE";
export const ENCODED_BYTECODE = "ENCODED_BYTECODE";
export const DECODED_BYTECODE = "DECODED_BYTECODE";
export const OPCODE_HANDLERS = "OPCODE_HANDLERS";